### ISSUE TITLE
Using Dalekfile is throwing issue

### ISSUE THREAD

**Issue by mischah** [dalekjs/dalek#121]
Using multiple browsers via commandline is working like a charme:

```
$ dalek test/test.js -b chrome,phantomjs
```

---

But using Dalekfile is throwing an error.

Content of `Dalekfile.json`:

```
{ "browsers": ["chrome", "phantomjs"] }
```

Firing dalek from terminal:

```
$ dalek test/test.js
```

---

**Error Message**

```
/Users/mkuehnel/Projects/dalekjs-hackathon/node_modules/dalekjs/lib/dalek.js:333
    this.driverEmitter.emit('killAll');
                       ^
TypeError: Cannot call method 'emit' of undefined
    at Object.Dalek._shutdown (/Users/mkuehnel/Documents/Projects/dalekjs-hackathon/node_modules/dalekjs/lib/dalek.js:333:24)
    at process.EventEmitter.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```

**Comment by brandonbuttars** [comment]
Any news on this?  :)  Next version?
